### ISSUE TITLE
A "requirements.txt" file to install the dependencies conveniently

### ISSUE THREAD

**Issue by jimbozhang** [lenovo-voice/THE-2020-PERSONALIZED-VOICE-TRIGGER-CHALLENGE-BASELINE-SYSTEM#1]
Installing the dependencies would be more easier if a `requirements.txt` file be provided.

```bash
pip install -r requirements.txt
```

**Comment by jiay7** [comment]
These files are in the src and sv_part folder. Refer to KWS_README.md and SV_README.md for more details.
